language: node_js
node_js:
  - "8.0"
  - "7.0"
script:
  - npm t
  - cd ./docs
  - yarn
  - npm t
  - npm run build
  - cd ./server
  - yarn
  - npm run build
  - cd ../../templates
  - yarn
  - npm t
  - npm run build
  - cd ./server
  - yarn
  - npm run build
